DROP DATABASE IF EXISTS quickdecks;
CREATE DATABASE quickdecks;

USE quickdecks;

CREATE TABLE flashcards (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE questions (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  flashcards INT,
  FOREIGN KEY (flashcards)
  REFERENCES flashcards(id)
  ON DELETE SET NULL
);


CREATE TABLE quiz (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE results (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  quiz INT,
  FOREIGN KEY (quiz)
  REFERENCES quiz(id)
  ON DELETE SET NULL
);


CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE user_names (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  user INT,
  FOREIGN KEY (user)
  REFERENCES user(id)
  ON DELETE SET NULL
);